name: Auto Update News

on:
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 3 点（北京时间上午11点）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run news update script
        run: node fetch-news.js

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add news.html
          git commit -m "auto: update news"
          git push